### ISSUE TITLE
Add a README file.

### ISSUE THREAD

**Issue by BrunoSilvaFreire** [Caetanopatrick/DataQuest_projects#1]
README files are one of the many things you can do to make your repository more appealing to contributors or viewers.  

They are markdown files that serve as a summary of your project and are displayed at your project's home page.  

For example, [this](https://github.com/LunariStudios/OverEditor/blob/master/README.md) is [OverEditor](https://github.com/LunariStudios/OverEditor)'s README.  

Here also some links that might also be useful:
* [GitHub resources](https://resources.github.com/)
* [Project guidelines](https://github.com/elsewhencode/project-guidelines)
* [Git best practices](https://gist.github.com/pandeiro/1552496)  

GL;HF!

**Comment by Caetanopatrick** [comment]
Done
